### ISSUE TITLE
OCM CLI End2End Test Suite

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#319]
**Description**
To validate the OCM CLI, as well as the specification itself, and to ensure that no incompatible changes are introduced going forward, an End2End Test Suite needs to be defined, technically set-up and documented. The test suite must at least cover the following actions:

- [x] Creation of a new component (based on or even same as the podinfo component) using the OCM CLI 
  - [x] adding resources
  - [x] adding sources
  - [x] adding component references
  - [x] signing
  - [x] verification

- [x] Uploading the component to an OCI Registry
- [x] Downloading the component from an OCI Registry
- [ ] Deploying the component, including validation of deployment (e.g. podinfo coming up ? configuration working as expected ?)
- [ ] Updating the component to a new version, including validation of deployment (e.g. podinfo showing latest version ? configuration working as expected ?)

The executed individual steps should be aligned with https://github.com/open-component-model/ocm/issues/347 (task for an End2End Test Suite using the OCM Controllers).

The following subtasks also have to be clarified:
- [x] Decide on the technology to be used to define and run the test suite(s) 
- [x] Create/Configure a workflow (Github Action ?) to ensure the test suites run e.g. nightly / on PR merge on main branch
- [x] The results of that test suite need to available centrally, like positive and negative test results
- [x] Summary of the latest test results should be posted in Github, e.g. for stakeholders
- [x] The test suite needs to be well documented (describing how it is setup technically, how it is executed, what exactly is executed and so on)

**Comment by jensh007** [comment]
Proposal: Have independent actions for Flux controllers and CLI.

Proposal for a first working package OCM CLI:

- Execute tests as a github action
- use a local OCI registry (e.g. from docker)
- use a "containerized service" in github action
- Checkout main
- Compile OCM
- Execute tests

Clarification needed:

- Data volume for oci registry, size and technology (local files, S3 backend, ...)
- TLS setup
- Technology for test suite
- How to run tests locally for debugging issues

**Comment by phoban01** [comment]
A couple of interesting go modules designed for testing CLIs:

- https://github.com/google/go-cmdtest (allows for in-process CLI execution)
- https://pkg.go.dev/gotest.tools/v3/icmd

**Comment by jensh007** [comment]
Are we sure that we really want to test deployment from cli? What should be the deployment framework in this case? toi? I am not sure that this should be priority.

Suggest to add transport tests:

- Create transport archive CTF
- Transport CTF from A to B
- Verify that that CTF in B is same as A
- optional test with "byValue" and recursively

**Comment by In-Ko** [comment]
all done, one thing we discussed: Adding some kind of notification, for now a message in our Slack Channel.
