### ISSUE TITLE
OCM Controllers End2End Test Suite

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#347]
**Description**
To validate the OCM Controllers, as well as the specification itself, and to ensure that no incompatible changes are introduced going forward, an End2End Test Suite needs to be defined, technically set-up and documented. The test suite must at least cover the following actions:

- [x] verification
- [x] Uploading the component to an OCI Registry
- [ ] Downloading the component from an OCI Registry
- [x] Deploying the component, including validation of deployment (e.g. podinfo coming up ? configuration working as expected ?)
- [x] Updating the component to a new version, including validation of deployment (e.g. podinfo showing latest version ? configuration working as expected ?)

The executed individual steps should be aligned with https://github.com/open-component-model/ocm/issues/319 (task for an End2End Test Suite using the OCM CLI).

The following subtasks also have to be clarified:
- [x] Decide on the technology to be used to define and run the test suite(s). This has been decided in the meantime, we will use https://github.com/open-component-model/ocm-e2e-framework to execute the tests for the OCM Controllers. Also see https://github.com/open-component-model/ocm-controller/issues/146
- [x] Create/Configure a workflow to ensure the test suites run e.g. nightly / on PR merge on main branch
- [x] The results of that test suite need to available centrally, like positive and negative test results
- [x] Summary of the latest test results should be posted in Github, e.g. for stakeholders
- [ ] The test suite needs to be well documented (describing how it is setup technically, how it is executed, what exactly is executed and so on)

**Comment by shivenduverma-sap** [comment]
- Added Status of last e2e test run in Readme.md
- Scheduled an everyday run for e2e tests 
- Added Passed, Failed, Skipped, Errors, total tests, etc. status to e2e test logs

https://github.com/open-component-model/ocm-controller/pull/186

**Comment by shivenduverma-sap** [comment]
- Added e2e Test for Component Upload To Local OCI Registry

https://github.com/open-component-model/ocm-controller/pull/191

**Comment by shivenduverma-sap** [comment]
- Added notifications for e2e test failures via ocm-github slack bot

https://github.com/open-component-model/ocm-controller/pull/192

**Comment by shivenduverma-sap** [comment]
- Refactored 1st test to also check reason along with ready condition
- Refactored 2nd test to also check successful component version conditions
- Added Test for signing and verification of components
- Added Test for signing of component and verification via invalid key in test

https://github.com/open-component-model/ocm-e2e-framework/pull/21
https://github.com/open-component-model/ocm-controller/pull/207

**Comment by Skarlso** [comment]
- [ ] Create a `Localization` object and verify it has correctly modified the Image in the deployment file
- [ ] Create a `Configuration` object and verify it has correctly modified the config data
- [ ] Create a `Resource` object and validate the created snapshot content
- [ ] Check the `ComponentDescriptor` object for resources

**Comment by shivenduverma-sap** [comment]
https://github.com/open-component-model/ocm-controller/pull/221

- Refactored OCM pipeline test:
  - Added/refactored OCM pipeline validation for all 3 deployments
  - Added test for component descriptor, nested component descriptors
  - Added configData<->Configuration changes for all deployments

- Refactored Signing Test:
  - Merged signing failed & successful signing into 1 test
  - Creates 3 deployments like test 1

- Fixed (hopefully) the ocm-controller e2e tests notifications on slack
- Minor error message refactoring
