### ISSUE TITLE
Add Signing & Signature Verification to OCM Client / OCM Controller

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#42]
**Description**
Based on the Signing & Signature Verification Specification (see issue https://github.com/gardener/ocm-spec/issues/5 ), this feature needs to be added to the OCM library, used by the OCM Client(s).

This epic contains several sub-tasks. Most of them are already available (like the initial creation and verification of the signatures), but some rework is needed / some leftovers exist.
- [ ] ~#115~ 
- [x] open-component-model/ocm#201

@mandelsoft :  Can you add further leftover or rework tasks which need to be done for this Epic please ?

**Done Criteria**
- [x] Signing Support is available as library
- [x] Signature Verification is available as library
- [x] The whole Signing and Verification flow is demo'ed to the Team (in the Review or a dedicated meeting), using an OCM Client (CLI or Controller)

**Comment by robertwol** [comment]
it has been decided to keep #115 "on hold" until necessary. 
For now, it has been removed from the scope of this issue so Epic can be closed.
A follow-up user story will be created to address topics related to Parallel Archive signing (#460)
