### ISSUE TITLE
Improve and extend OCM Specification

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#6]
**Description**
The official OCM Specification needs to be improved and extended. This includes:
- Working on the leftovers, maintained at https://github.com/gardener/ocm-spec/blob/main/doc/proposal/leftovers.md, which are partially already discussed improvements, which should be integrated into the Spec, and partially also things which need discussion and agreement within the team, and after that also integration into the spec itself.
- Add further ToDos to this list (which are actively being discussed in various places like Slack, GitHub Discussions). We need a central place where to capture all leftovers / ToDos / Improvements for the OCM Spec. Let's agree on one and maintain everything there.
- Think about a possible restructuring of the Spec, to make it easily consumable. This should include a Specification Schema Browser". A good example can be found here: https://cyclonedx.org/docs/1.4/json/#bomFormat
- Finally, move from "proposal state" to real, official spec

**Done Criteria**
- [x] Structure and current WiP-State of OCM Spec has been shared with everyone
- [x] initial onboarding towards specification work (suggestion: organise a 1hr meeting)
- [ ] Leftovers and further ToDos have been discussed and integrated into the Specification, at least all of these have been added to https://github.com/gardener/ocm-spec/blob/main/doc/proposal/leftovers.md, to have a central place where we gather them all
- [x] Proposal for a possible restructuring of the OCM Spec has been communicated and if agreed by everyone, also integrated into the OCM Spec
- [x] After all of the above is done, the Spec is moved from "proposal" to an official place

**Comment by jensh007** [comment]
Contract chapter added.

**Comment by In-Ko** [comment]
Will close this now, we track individual tweaks / changes / improvements on the Spec in individual tasks.
